import React from "react";
import type { NextPage } from "next";
import Head from "next/head";

import { useData } from "../hooks/useData";
import { PrefecturesList } from "../components/PrefecturesList";
import { PopulationGraph } from "../components/PopulationGraph";

const Home: NextPage = () => {
  // FIXME: https://opendata.resas-portal.go.jp/api/v1/prefectures
  const { data: prefecturesData, isError: prefecturesIsError } = useData(
    "./dammy/prefectures.json"
  );

  // FIXME: https://opendata.resas-portal.go.jp/api/v1/population/composition/perYear
  const { data: seriesData, isError: seriesIsError } = useData(
    "./dammy/perYear.json"
  );

  return (
    <>
      <Head>
        <title>都道府県別の総人口推移グラフ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <h1 className="text-xl md:text-2xl text-center bg-red-200 p-4 md:p-8 font-semibold">
          都道府県別の総人口推移グラフ
        </h1>

        <div className="container mx-auto px-4 py-8">
          <h2 className="text-lg font-semibold mb-4">都道府県</h2>
          {!prefecturesIsError && (
            <PrefecturesList prefectures={prefecturesData} />
          )}
        </div>

        <div className="container mx-auto px-4 py-8">
          <h2 className="text-lg font-semibold mb-4">人口数</h2>
          {!seriesIsError && <PopulationGraph series={seriesData} />}
        </div>
      </>
    </>
  );
};

export default Home;
