import type { NextPage } from "next";
import Head from "next/head";
import { Prefectures } from "./prefectures";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>都道府県別の総人口推移グラフ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <h1 className="text-xl md:text-2xl text-center bg-red-200 p-4 md:p-8 font-semibold">
          都道府県別の総人口推移グラフ
        </h1>
        <div className="container mx-auto px-4 py-8">
          <h2 className="text-lg font-semibold mb-4">都道府県</h2>
          <div className="grid grid-cols-4 gap-4">
            {Prefectures.map((prefecture) => (
              <div>
                <label>
                  <input
                    type="checkbox"
                    name="prefectures"
                    value={prefecture}
                  />
                  <span className="pl-2">{prefecture}</span>
                </label>
              </div>
            ))}
          </div>
        </div>
      </>
    </>
  );
};

export default Home;
